name: cloudrun-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-west1-a
  GKE_CLUSTER: example-gke-cluster
  IMAGE: gke-test
    
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
        export_default_credentials: true

    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    # Build the Docker image
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GKE_PROJECT }}
        gcloud builds -t gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE:${{ github.sha }} \
          --build-arg GITHUB_SHA="${{ github.sha }}" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
        
    - name: Publish
      run: |
        gcloud config set project ${{ secrets.GKE_PROJECT }}
        gcloud builds -t gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE:${{ github.sha }} \
          --build-arg GITHUB_SHA="${{ github.sha }}" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
        docker push gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE:${{ github.sha }}
        gcloud config set run/region us-central1
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud run deploy $IMAGE:${{ github.sha }} --image gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE:${{ github.sha }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 256M
